version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro  # Montar el script de inicialización.
    ports:
      - "80:27017"

  flask_app:
    image: python:3.9
    container_name: flask_app
    working_dir: /app
    volumes:
      - .:/app
    command: python run.py
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./requirements.txt:/app/requirements.txt
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sh", "-c", "pip install -r requirements.txt && python run.py"]

volumes:
  mongo_data:
    external: true
